// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqKuQ-qaiOuEJK1WS0A-n7Ekagl6d_rWo',
    appId: '1:173715126458:web:3985e9da8e39b50d676a83',
    messagingSenderId: '173715126458',
    projectId: 'notesappfirebase-12b73',
    authDomain: 'notesappfirebase-12b73.firebaseapp.com',
    storageBucket: 'notesappfirebase-12b73.firebasestorage.app',
    measurementId: 'G-NJDK933ZSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhPvxdSG6AJfX95bveklj9MKRLyXvM03k',
    appId: '1:173715126458:android:f89dec3076f69515676a83',
    messagingSenderId: '173715126458',
    projectId: 'notesappfirebase-12b73',
    storageBucket: 'notesappfirebase-12b73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCww6GgjU1qmQGXE1PvmXkX04cnYM5RxCk',
    appId: '1:173715126458:ios:f21c00b20af8aba9676a83',
    messagingSenderId: '173715126458',
    projectId: 'notesappfirebase-12b73',
    storageBucket: 'notesappfirebase-12b73.firebasestorage.app',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCww6GgjU1qmQGXE1PvmXkX04cnYM5RxCk',
    appId: '1:173715126458:ios:f21c00b20af8aba9676a83',
    messagingSenderId: '173715126458',
    projectId: 'notesappfirebase-12b73',
    storageBucket: 'notesappfirebase-12b73.firebasestorage.app',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqKuQ-qaiOuEJK1WS0A-n7Ekagl6d_rWo',
    appId: '1:173715126458:web:c06fde8a80fa780d676a83',
    messagingSenderId: '173715126458',
    projectId: 'notesappfirebase-12b73',
    authDomain: 'notesappfirebase-12b73.firebaseapp.com',
    storageBucket: 'notesappfirebase-12b73.firebasestorage.app',
    measurementId: 'G-FQ9MQXWZ1K',
  );
}
